### ISSUE TITLE
miss js file "uia-wafermap.js 

### ISSUE THREAD

**Issue by johnhuang669** [uia4w/uia-wafermap#1]
miss js file "uia-wafermap.js " ??  please help....

**Comment by zhaoleilei004** [comment]
Can you explain the principle briefly?What do I need to do when I need to use your code?

**Comment by gazer2kanlin** [comment]
* I fixed some bugs and updated README to describe how to __build__ and __test__ the project.
* The __uia-wafermap.js__ in the __dist__ folder is my last build. You can try it.
* open __index.html__, you can see the wafer map generated by __js/sample.js__.
