### ISSUE TITLE
Hello, can you generate a wafer diagram of any shape defect? Can the bottom rectangle pattern be removed when saving the police officer map

### ISSUE THREAD

**Issue by ghost** [uia4w/uia-wafermap#2]
Hello, can you generate a wafer diagram of any shape defect? Can the bottom rectangle pattern be removed when saving the police officer map

**Comment by gazer2kanlin** [comment]
Detail refer to the README file and sample2.js

1. A new helper method named __diePalette(function)__ which can customize color depending on the grade of dies. You can just draw 'failed' dies.
2. Default the dies grid will not be drawn. 
3. Use helper method __visibility(id, state)__ to change visibility of some elements.

**Comment by gazer2kanlin** [comment]
1. disable circle or rectangle
    ```js
    var shotmap = uia.shotmap('wafer2')
        .circleBackground(false)
        .dieRect(false)
    ```
2. right click to save to an image, support full map, zoom in/out
