### ISSUE TITLE
If possible support zoom please.

### ISSUE THREAD

**Issue by OneNX0307** [uia4w/uia-wafermap#5]

**Comment by robyle** [comment]
> _No description provided._

welcome have a chat on VX:robortly

**Comment by gazer2kanlin** [comment]
I reimplemented the project and used PIXI.js to renderer the map. 

The last version adds some features including
* wheel to control zoom in/out
* double click to zoom in.
* drag and drop the map
* zoom functions (in/out/reset).
* two mode for coloring dies.
